import {
  Siren,
  AlertTriangle,
  CheckCircle2,
  Sparkles,
} from "lucide-react";
import { useMineContext } from "../context/MineDataContext";
import AlertCard from "../components/alerts/AlertCard";

function formatTime(timestamp) {
  return new Date(timestamp).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
}

function toAlertCardShape(alert) {
  return {
    id: alert.id,
    title: alert.title,
    message: alert.message,
    severity: alert.type,
    worker: alert.worker,
    zone: alert.zone,
    time: formatTime(alert.time),
    acknowledged: alert.acknowledged,
  };
}

function Alerts() {
  const { alerts, acknowledgeAlert } = useMineContext();

  const currentAlerts = alerts.filter((alert) => alert.kind === "current");
  const predictiveAlerts = alerts.filter((alert) => alert.kind === "predictive");

  const activeCritical = alerts.filter((alert) => alert.type === "Critical" && !alert.acknowledged).length;
  const activeWarnings = alerts.filter((alert) => alert.type !== "Critical" && !alert.acknowledged).length;
  const resolvedCount = alerts.filter((alert) => alert.acknowledged).length;

  return (
    <div className="mx-auto max-w-[1400px] space-y-5">
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-red-400">
          Emergency Center
        </p>
        <h1 className="mt-1 text-2xl font-bold text-white">Alerts</h1>
        <p className="mt-1 text-xs text-slate-500">
          Current safety alerts and AI-predicted early warnings generated by SafeMine.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="rounded-2xl border border-red-500/10 bg-red-500/[0.04] p-5">
          <Siren className="text-red-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Critical</p>
          <p className="mt-1 text-3xl font-bold text-red-400">{activeCritical}</p>
        </div>

        <div className="rounded-2xl border border-amber-500/10 bg-amber-500/[0.04] p-5">
          <AlertTriangle className="text-amber-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Warnings</p>
          <p className="mt-1 text-3xl font-bold text-amber-400">{activeWarnings}</p>
        </div>

        <div className="rounded-2xl border border-emerald-500/10 bg-emerald-500/[0.04] p-5">
          <CheckCircle2 className="text-emerald-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Resolved</p>
          <p className="mt-1 text-3xl font-bold text-emerald-400">{resolvedCount}</p>
        </div>
      </div>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <Siren size={15} className="text-red-400" />
          <h2 className="text-sm font-semibold text-white">Current Alerts</h2>
          <span className="text-[10px] text-slate-600">Confirmed safety threshold violations</span>
        </div>

        {currentAlerts.length === 0 ? (
          <p className="rounded-2xl border border-white/[0.06] bg-[#0c121c] p-6 text-center text-xs text-slate-500">
            No confirmed critical alerts right now.
          </p>
        ) : (
          <div className="space-y-3">
            {currentAlerts.map((alert) => (
              <AlertCard key={alert.id} alert={toAlertCardShape(alert)} onAcknowledge={acknowledgeAlert} />
            ))}
          </div>
        )}
      </section>

      <section className="space-y-3">
        <div className="flex items-center gap-2">
          <Sparkles size={15} className="text-cyan-400" />
          <h2 className="text-sm font-semibold text-white">Early Warnings — Predicted Risk</h2>
          <span className="text-[10px] text-slate-600">Trend-based predictions before a threshold is crossed</span>
        </div>

        {predictiveAlerts.length === 0 ? (
          <p className="rounded-2xl border border-white/[0.06] bg-[#0c121c] p-6 text-center text-xs text-slate-500">
            No early warnings — all sensor trends are stable.
          </p>
        ) : (
          <div className="space-y-3">
            {predictiveAlerts.map((alert) => (
              <AlertCard key={alert.id} alert={toAlertCardShape(alert)} onAcknowledge={acknowledgeAlert} />
            ))}
          </div>
        )}
      </section>
    </div>
  );
}

export default Alerts;
