import {
  AlertTriangle,
  Siren,
  Wind,
  Flame,
  Activity,
  CheckCircle2,
} from "lucide-react";

const alerts = [
  {
    id: "ALT-1024",
    title: "Critical methane level",
    worker: "Aman Rawat · SM-004",
    zone: "Zone C",
    value: "78 ppm",
    time: "2 min ago",
    type: "Critical",
    icon: Wind,
  },
  {
    id: "ALT-1023",
    title: "High temperature",
    worker: "Vikas Negi · SM-003",
    zone: "Zone B",
    value: "42.8°C",
    time: "5 min ago",
    type: "Warning",
    icon: Flame,
  },
  {
    id: "ALT-1022",
    title: "Abnormal movement",
    worker: "Naveen Rana · SM-007",
    zone: "Zone B",
    value: "0.82g",
    time: "8 min ago",
    type: "Warning",
    icon: Activity,
  },
];

function Alerts() {
  return (
    <div className="mx-auto max-w-[1400px] space-y-5">
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-red-400">
          Emergency Center
        </p>
        <h1 className="mt-1 text-2xl font-bold text-white">Alerts</h1>
        <p className="mt-1 text-xs text-slate-500">
          Real-time safety alerts generated by the SafeMine system.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
        <div className="rounded-2xl border border-red-500/10 bg-red-500/[0.04] p-5">
          <Siren className="text-red-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Critical</p>
          <p className="mt-1 text-3xl font-bold text-red-400">1</p>
        </div>

        <div className="rounded-2xl border border-amber-500/10 bg-amber-500/[0.04] p-5">
          <AlertTriangle className="text-amber-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Warnings</p>
          <p className="mt-1 text-3xl font-bold text-amber-400">2</p>
        </div>

        <div className="rounded-2xl border border-emerald-500/10 bg-emerald-500/[0.04] p-5">
          <CheckCircle2 className="text-emerald-400" size={20} />
          <p className="mt-3 text-[10px] uppercase text-slate-500">Resolved Today</p>
          <p className="mt-1 text-3xl font-bold text-emerald-400">17</p>
        </div>
      </div>

      <div className="space-y-3">
        {alerts.map((alert) => {
          const Icon = alert.icon;
          const critical = alert.type === "Critical";

          return (
            <div
              key={alert.id}
              className={`rounded-2xl border p-5 ${
                critical
                  ? "border-red-500/15 bg-red-500/[0.04]"
                  : "border-amber-500/10 bg-[#0c121c]"
              }`}
            >
              <div className="flex flex-col gap-4 md:flex-row md:items-center">
                <div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${
                  critical ? "bg-red-400/10 text-red-400" : "bg-amber-400/10 text-amber-400"
                }`}>
                  <Icon size={20} />
                </div>

                <div className="flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <h3 className="text-sm font-semibold text-white">{alert.title}</h3>
                    <span className={`rounded-full px-2 py-0.5 text-[8px] font-bold ${
                      critical ? "bg-red-400/10 text-red-400" : "bg-amber-400/10 text-amber-400"
                    }`}>
                      {alert.type}
                    </span>
                  </div>

                  <p className="mt-1 text-[10px] text-slate-500">
                    {alert.worker} · {alert.zone}
                  </p>
                </div>

                <div className="md:text-right">
                  <p className="text-sm font-bold text-white">{alert.value}</p>
                  <p className="mt-1 text-[9px] text-slate-600">{alert.time}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

export default Alerts;